# Generated by Django 3.0.3 on 2023-03-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dff_backend', '0002_auto_20230311_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dff_backend.ImageAlbum'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_inventory',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='dff_backend.ProductInventory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='dff_backend.Category'),
        ),
    ]
